# coding: utf-8

# flake8: noqa
"""
    Passage Management API

    Passage's management API to manage your Passage apps and users.

    The version of the OpenAPI document: 1
    Contact: support@passage.id
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from passageidentity.models.updateMagicLinkAuthMethod import UpdateMagicLinkAuthMethod
from passageidentity.models.updatePasskeysAuthMethod import UpdatePasskeysAuthMethod
from passageidentity.models.updateOtpAuthMethod import UpdateOtpAuthMethod
