name: Lint, Format, and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          args: check
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          args: format --check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Test
        env:
          CI: true
        run: pytest
  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@v2
        with:
          require: write
        id: check_permission
      - name: Trigger E2E Workflow in backend-sdk-tests and Wait
        if: ${{ steps.check_permission.outputs.require-result == 'true' }}
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: passageidentity
          repo: backend-sdk-tests
          workflow_file_name: integration-tests-complete.yml
          github_token: ${{ secrets.BE_SDK_PAT }}
          # github.head_ref is only available on PR events, while github.ref_name provides the branch name on other events
          client_payload: >-
            {
              "target_sdk":"python",
              "use_test_release":true,
              "sdk_branch_ref":"${{ github.head_ref || github.ref_name }}"
            }